name: flutter_gallery
description: "致力打造全组件（含路由、状态管理、请求等）demo"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

# 依赖
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1 # 网络请求
  get: ^4.6.6 # 状态管理 + 路由管理（新手不建议 忽略了很多flutter原始方法）
  provider: ^6.1.2 # 状态管理
  go_router: ^13.2.1 # 路由管理
  share_plus: ^6.3.4 # 文字分享
  fluttertoast: ^8.2.4 # 轻提示
  carousel_slider: ^4.2.1 # 走马灯
  webview_flutter: ^4.7.0 # webview
  cupertino_icons: ^1.0.6 # 苹果风格图标
  flutter_highlight: ^0.7.0 # 代码高亮
  flutter_screenutil: ^5.9.0 # 适应屏幕和字体大小
  shared_preferences: ^2.2.2 # 本地存储
  connectivity_plus: ^5.0.2 # 判断是否网络连接/可以区分蜂窝和WiFi连接
  getuiflut: ^0.2.27 # 个推 - 消息推送

# 开发依赖
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # 图片配置
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/banner/
    - lib/pages/component/widgets/StatelessWidget/
    - lib/pages/component/widgets/StatefulWidget/
    - lib/pages/component/widgets/SliverWidget/
    - lib/pages/component/widgets/ProxyWidget/
    - lib/pages/component/widgets/OtherWidget/
    - lib/pages/component/widgets/MultiChildRenderObjectWidget/
    - lib/pages/component/widgets/SingleChildRenderObjectWidget/


  # 自体配置
  fonts:
    - family: AlibabaIcon
      fonts:
        - asset: assets/fonts/iconfont.ttf

